secadmin/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from sec import views, vul, weeklearn, doorcard
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home),
    url(r'^submit_week_learn/', weeklearn.submit_week_learn),
    url(r'^doorcard/', doorcard.door),
    url(r'^doorclose/', doorcard.close),
    url(r'^changepersion/', views.change_persion),
    url(r'^week_list/', weeklearn.week_list),
    url(r'^submit/', views.submit),
    url(r'^vul_review/$', vul.vul_review),
    url(r'^vul_add/$', vul.vul_add),
    url(r'^vul_reviewed/', vul.vul_reviewed),
    url(r'^my_vul/', vul.my_vul),
    url(r'^ranking/', vul.ranking),
    url(r'^login/', views.user_login),
    url(r'^changeblog/', views.changeblog),
    url(r'^random_week/', views.random_week),
    url(r'^change/(\d+)/', views.change, name='change_id'),
    url(r'^register/', views.register),
    url(r'^blog/(\d+)/$', views.weekblog, name='week'),
    url(r'^myblog/(\d+)/$', views.myblog, name='user_id'),
    url(r'^logout/', views.user_logout),
    url(r'^search/', views.search),
    url(r'^classification/', views.classification),
    url(r'^onduty/', views.onduty),
    url(r'^ctflerning/', views.ctflerning),
    url(r'^book/', views.book),
    url(r'^lend/', views.lend),
    url(r'^back/', views.back),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sec/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
#
class BlogDirection(models.Model):
    DIRECTION_CHOICES = (
        ('sec', '网络安全'),
        ('dat', '大数据'),
    )
    name = models.CharField("名称", max_length=10)
    direction = models.CharField("方向", max_length=10, choices=DIRECTION_CHOICES)

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.name

    class Meta:
        verbose_name_plural = '博客方向'


class Blog(models.Model):
    blog_user = models.ForeignKey(User)
    content = models.TextField("博客标题", null=False)
    direction = models.CharField("方向（已弃用，移植到新的博客方向）", max_length=30, null=True)
    new_direction = models.ForeignKey(BlogDirection, null=True)
    url = models.CharField(max_length=300)
    time = models.DateTimeField(auto_now_add=True)
    week = models.IntegerField("周数")

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.content

    class Meta:
        verbose_name_plural = '博客'
        ordering = ["-time"]


class CTF_learning(models.Model):
    title = models.CharField(max_length=30)
    url = models.CharField(max_length=100)
    type = models.CharField(max_length=20)

    class Meta:
        # 末尾不加s
        verbose_name_plural = 'CTF资料库'

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.title


class ON_DUTY(models.Model):
    time = models.CharField(max_length=30)
    name = models.CharField(max_length=100)

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.time

    class Meta:
        verbose_name_plural = '值班表'


class Book(models.Model):
    TYPE_CHOICES = (
        ('web', '网络'),
        ('re', '逆向'),
        ('program', '开发'),
        ('system', '系统'),
        ('other', '其他'),
    )
    name = models.CharField(max_length=30)
    storage_time = models.DateTimeField(auto_now_add=True)
    lend_time = models.DateTimeField(null=True, blank=True)
    lend_people = models.ForeignKey(User, null=True, blank=True)
    is_lend = models.BooleanField(default=False)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    image = models.ImageField(upload_to='bookimages/%Y/%m', verbose_name='缩略图', null=True, blank=True)

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.name

    class Meta:
        verbose_name_plural = '图书管理'


class VulRecord(models.Model):
    TYPE_CHOICES = (
        ('sql', 'SQL注入'),
        ('xss', 'XSS'),
        ('upload', '文件上传'),
        ('shell', '命令执行'),
        ('ssrf', 'SSRF'),
        ('csrf', 'CSRF'),
        ('code', '代码注入'),
        ('delete', '任意删除'),
        ('download', '任意下载'),
        ('logic', '逻辑漏洞'),
        ('unacc', '未授权访问'),
    )
    vul_finder = models.ForeignKey(User, related_name="finder")
    vul_url = models.CharField(max_length=100)
    vul_payload = models.TextField(null=True)
    vul_type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    vul_process = models.TextField()
    vul_score = models.IntegerField()
    vul_review = models.BooleanField(default=False)
    vul_review_people = models.ForeignKey(User, null=True, related_name="reviewer")
    vul_time = models.DateTimeField(auto_now_add=True)
    vul_image = models.ImageField(upload_to='vul/%Y/%m', verbose_name="复现图", null=True, blank=True)
    vul_fix = models.TextField(null=True)
    vul_frist = models.BooleanField(default=False)
    AC_CHOICE = {
        ('3.5', '高'),
        ('0.61', '中'),
        ('0.71', '低'),

    }
    AU_CHOICE = {
        ('0.45', 'multiple'),
        ('0.56', 'single'),
        ('0.704', 'none'),

    }
    vul_ac = models.CharField("攻击复杂度", max_length=10, choices=AC_CHOICE, null=True)
    vul_au = models.CharField("认证", max_length=10, choices=AU_CHOICE, null=True)

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return self.vul_url + "：" + self.get_vul_type_display()

    class Meta:
        verbose_name_plural = '漏洞记录管理'


class WeekTask(models.Model):
    DIRECTION_CHOICES = (
        ('sec', '网络安全'),
        ('dat', '大数据'),
    )
    task_content = models.TextField()
    task_week = models.IntegerField()
    task_direction = models.CharField("方向", max_length=10, choices=DIRECTION_CHOICES, default='sec')

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return str(self.task_week)

    class Meta:
        verbose_name_plural = '每周任务'


class WeekLearn(models.Model):
    learner = models.ForeignKey(User)
    learn_image = models.ImageField(upload_to='learn/%Y/%m', verbose_name="复现图", null=True, blank=True)
    learn_time = models.DateTimeField(auto_now_add=True)
    learn_task = models.ForeignKey(WeekTask, null=True)

    class Meta:
        verbose_name_plural = '每周基础学习管理'


class UserProfile(models.Model):
    DIRECTION_CHOICES = (
        ('sec', '网络安全'),
        ('dat', '大数据'),
    )
    user = models.OneToOneField(User)  # 关联自带的User结构
    student_id = models.CharField("学号", max_length=10)
    direction = models.CharField("方向", max_length=10, choices=DIRECTION_CHOICES, default='sec')
    qq = models.CharField("QQ", max_length=14, null=True)
    phone = models.CharField("联系电话", max_length=12, null=True)
    grade = models.IntegerField("入学年份")

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return str(self.user)

    class Meta:
        verbose_name_plural = '个人信息'


class DoorCard(models.Model):
    STATUS_CHOICES = (
        ('in', '正在实验室并且已开门'),
        ('out', '离开实验室并已关门'),
        ('unknow', '离开实验室走时未关门')
    )

    owner = models.OneToOneField(User)
    number = models.CharField('编号', max_length=10)
    get_time = models.DateTimeField(auto_now=True)
    status = models.CharField("门卡状态", max_length=10, choices=STATUS_CHOICES, default='unknow')

    def __str__(self):  # 在Python3中用 __str__ 代替 __unicode__
        return str(self.number)

    class Meta:
        verbose_name_plural = '门卡管理'

templates/base.html
<!DOCTYPE HTML>

<html>
<head>
    <title>711实验室博客提交平台</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="/static/assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/static/assets/css/main.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="/static/assets/css/ie8.css" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="/static/assets/css/ie9.css" /><![endif]-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link rel="stylesheet" href="/static/assets/css/form-elements.css">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="/static/auto.ico" media="screen" />
</head>
<body class="landing">

<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Header -->
    <header id="header" class="alt">
        <h1><a href="/">711实验室博客提交平台</a></h1>
        <nav id="nav">
            <ul>
                <li class="special">
                    <a href="#menu" class="menuToggle"><span>Menu</span></a>
                    <div id="menu">
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/ctflerning">CTF资料库</a></li>
                            <li><a href="/book">图书管理</a></li>
                            <li><a href="/onduty/">值班表</a></li>
                            <li><a href="/ranking/">积分榜</a></li>
                            <li><a href="/doorcard/">门卡管理</a></li>


                            {% if request.session.username %}
                                <li><a href="/submit">博客提交</a></li>
                                <li><a href="/changepersion">个人信息修改</a></li>
                                <li><a href="/submit_week_learn">基础学习提交</a></li>
                                <li><a href="/week_list">基础学习提交RANk</a></li>
                                <li><a href="/myblog/{{ request.session.id }}/">我的提交</a></li>
                                <li><a href="/changeblog/">修改我的提交</a></li>
                                <li><a href="/search/">博客搜索</a></li>
                                <li><a href="/classification/">博客分类</a></li>
                                <li><a href="/vul_add/">提交漏洞</a></li>
                                <li><a href="/my_vul/">我提交的漏洞</a></li>
                                <li><a href="/vul_reviewed/">已审核漏洞</a></li>
                                {% if request.user.is_staff %}
                                <li><a href="/vul_review/">待审核漏洞</a></li>

                                {% endif %}

                            <li><a href="/logout">登出</a></li>
                                {% else %}

                                <li><a href="/login">登录</a></li>
                            <li><a href="/register">注册</a></li>
                            {% endif %}

                        </ul>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    {% block root %}

    {% endblock %}
    					<footer id="footer">
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
						</ul>
						<ul class="copyright">
							<li>&copy; 版权所有711实验室</li><li>
						</ul>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.scrollex.min.js"></script>
			<script src="/static/assets/js/jquery.scrolly.min.js"></script>
			<script src="/static/assets/js/skel.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="/static/assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="/static/assets/js/main.js"></script>


	</body>
</html>

templates/book.html
{% extends 'base.html' %}
{% block root %}
	<div id="page-wrapper">



				<!-- Main -->
					<article id="main">
						<header>
							<h2>图书</h2>

						</header>
						<section class="wrapper style5">
							<div class="inner">
								<section>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>

													<th>书名</th>
                                                    <th>图片</th>
													<th>是否借出</th>
                                                    <th>类型</th>
                                                    <th>借出时间</th>
                                                    <th>借出人</th>
                                                    <th>借阅</th>
												</tr>
											</thead>
											<tbody>
                                            {% for book in books %}
                                            <tr>
													<td>{{ book.name }}</td>
                                                    <td><img class="center-block thumbnail" src="/{{ book.image.url }}" alt="" height="100" width="80"/></td>
													<td>{% if book.is_lend %}已借出{% else %}未借出{% endif %}</td>
                                                    <td>{{ book.get_type_display }}</td>
													<td>{% if book.lend_time %}{{ book.lend_time|date:"Y-m-d H:i:s" }}{% else %}未借出{% endif %}</td>
                                                    <td>{{ book.lend_people.first_name }}</td>

                                                {% if request.session.username and book.lend_people.username == request.session.username %}
                                                <td><a href="/back?id={{ book.id }}" class="button special small">还书</a></td>
                                                    {% else %}
                                                     <td><a href="/lend?id={{ book.id }}" class="button special {% if book.is_lend %}disabled{% else %}small{% endif %}">借阅</a></td>
                                                {% endif %}


												</tr>
                                            {% endfor %}


											</tbody>
										</table>
									</div>
								</section>



							</div>
						</section>
					</article>

{% endblock %}

templates/changemyblog.html
{% extends 'base.html' %}
{% block root %}
	<div id="page-wrapper">



				<!-- Main -->
					<article id="main">
						<header>
							<h2>{{ request.session.username }}的博客</h2>

						</header>
						<section class="wrapper style5">
							<div class="inner">
								<section>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>

													<th>标题</th>
													<th>网址</th>
                                                    <th>方向</th>
                                                    <th>时间</th>
                                                    <th>修改</th>
												</tr>
											</thead>
											<tbody>
                                            {% for blog in blogs %}
                                            <tr>
                                                <form method="post" action="/change/{{ blog.id }}/">
                                                    <td><input  type="text"  name='content' value="{{  blog.content}}"></td>
													<td><input  type="text"  name='url' value="{{  blog.url}}"></td>
                                                    <td>{{  blog.new_direction}}</td>
													<td>{{ blog.time }}</td>
                                                    {% csrf_token %}
                                                    <td><input type="submit" class="button special" value="修改"></td>
												</tr>
                                                </form>
{#													<td>{{ blog.blog_user }}</td>#}

                                            {% endfor %}


											</tbody>
										</table>
									</div>
								</section>



							</div>
						</section>
					</article>

{% endblock %}

templates/classification.html
{% extends 'base.html' %}
{% block root %}
	<div id="page-wrapper">



				<!-- Main -->
					<article id="main">
						<header>
							<h2>博客分类</h2>
                            <form action="/classification/" method="post">
                                <select name="direction" id="demo-category">
														<option value="">- 学习内容方向 -</option>
														{% for direction in directions %}
                                                        <option value="{{ direction.id }}">{{ direction }}</option>
                                                        {% endfor %}
													</select>
                                <input type="submit" value="确定">
                                {% csrf_token %}
                            </form>

						</header>
						<section class="wrapper style5">
							<div class="inner">
								<section>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>

													<th>标题</th>
													<!--<th>网址</th>-->
                                                    <th>方向</th>
                                                    <th>时间</th>
												</tr>
											</thead>
											<tbody>
                                            {% for blog in blogs %}
                                            <tr>
{#													<td>{{ blog.blog_user }}</td>#}
													<td><a href="{{  blog.url}}" target="_blank">{{  blog.content}}</a></td>
                                                    <td>{{ blog.new_direction }}</td>
													<td>{{ blog.time }}</td>
												</tr>
                                            {% endfor %}


											</tbody>
										</table>
									</div>
								</section>



							</div>
						</section>
					</article>

{% endblock %}

templates/ctflerning.html
{% extends 'base.html' %}
{% block root %}
	<div id="page-wrapper">
				<!-- Main -->
					<article id="main">
						<header>
							<h2>CTF 学习资料库</h2>

						</header>
						<section class="wrapper style5">
							<div class="inner">
								<section>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>
													<th>标题</th>
													<th>类别</th>

												</tr>
											</thead>
											<tbody>
{#                                            {% for blog in blogs %}#}
{#                                            <tr>#}
{#													<td><a href="/myblog/{{ blog.blog_user.id }}/">{{ blog.blog_user }}</a> </td>#}
{#													<td><a href="{{  blog.url}}" target="_blank">{{  blog.content}}</a></td>#}
{#													<td>{{  blog.url}}</td>#}
{#                                                    <td>{{ blog.direction }}</td>#}
{#													<td>{{ blog.time }}</td>#}
{#												</tr>#}
{#                                            {% endfor %}#}
                                            {% for foo in ctf %}
                                                <tr>
                                            <td><a href="{{ foo.url }}/" target="_blank">{{ foo.title }}</a> </td>
													<td>{{ foo.type }}</td>
                                                </tr>
                                            {% endfor %}

											</tbody>
										</table>
									</div>
								</section>


							</div>
						</section>

					</article>

{% endblock %}

templates/doorcard.html
{% extends 'base.html' %}
{% block root %}
	<div id="page-wrapper">
				<!-- Main -->
					<article id="main">
						<header>
							<h2>门卡管理</h2>
                            <div align="center">
                                {% if user_card %}
                                    <h3>您的门卡编号是{{ user_card }}</h3>
                                <a href="?status=in" style="background-color:#27d318" class="button special" >开门</a>
                                 <a href="?status=out" style="background-color:#d3100d" class="button special" >卡离关门</a>
                                 <a href="?status=unknow" style="background-color:#d3c912" class="button special" >卡离未关门</a>
                                    {% else %}
                                        <form method="post">
                                            <select name="card" id="demo-category">
                                                <option value="">- 选择获得的门卡编号 -</option>
                                                {% for card in cards %}
                                                <option value="{{ card.id }}">{{ card.number }}</option>
                                                {% endfor %}
                                            </select>
                                        {% csrf_token %}
                                        <input type="submit" style="background-color:#27d318" class="button special" value="GET门卡">
                                        </form>
                                {% endif %}

                            </div>
						</header>
						<section class="wrapper style5">
							<div class="inner">
								<section>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>
													<th>门卡编号</th>
													<th>持卡人</th>
                                                    <th>状态最后变更时间</th>
                                                    <th>门卡状态</th>
												</tr>
											</thead>
											<tbody>
                                            {% for card in cards %}
                                            <tr>
													<td>{{ card.number }} </td>
													<td>{{  card.owner }}</td>
                                                    <td>{{ card.get_time | date:'Y-n-d H:i' }}</td>
													<td  {% if card.status == 'in' %}
                                                        style="background-color:#27d318"
                                                        {% elif card.status == 'out' %}
                                                        style="background-color:#d3100d"
                                                        {% elif card.status == 'unknow' %}
                                                        style="background-color:#d3c912"
                                                    {% endif %} >{{ card.get_status_display }}</td>
												</tr>
                                            {% endfor %}
											</tbody>
										</table>
									</div>
								</section>

							</div>
						</section>

					</article>

{% endblock %}

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>alert("{{ message }}");window.location.href='{{ url }}';{{ code }}</script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block root %}

				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<h2>711实验室综合管理平台</h2>
                            <h3>实验室是否开门 {% if door %}
                                ✅
                                {% else %}
                                ❌
                            {% endif %}</h3>
                 <a href="doorclose/" style="background-color:#d3100d" class="button special" >关门</a>

							<p>请提交本周博客<br />
							<!--site template freebie<br />-->
{#							crafted by <a href="http://123.206.74.236">taropowder</a>.</p>#}
							<ul class="actions">
								<li><a href="/submit" class="button special">博客提交</a></li>
							</ul>
						</div>
						<a href="#one" class="more scrolly">每周博客一览</a>
					</section>

				<!-- One -->
    {% for key in week_list %}
        <section id="one" class="wrapper style1 special">
						<div class="inner">
							<header class="major">
                                <h2><a href="/blog/{{ key }}/"> 第{{ key }}周博客一览</a></h2>
								<ul style="list-style-type:none">
                                    {% for m,k in week_content.items %}
                                    	{% ifequal key m %}
                                    		{% for v in k %}
                                    			<li><a href="{{ v.url }}"style="color:white;" target="_blank">{{ v.content }}</a></li>
                                    		{% endfor %}
                                    	{% endifequal %}
                                    {% endfor %}
								</ul>

							</header>
							<ul class="icons major">

                                <li><span class="icon fa-diamond major style1"><span class="label">Lorem</span></span></li>

{#                                    <li><span class="icon fa-heart-o major style2"><span class="label">Ipsum</span></span></li>#}
{#								<li><span class="icon fa-code major style3"><span class="label">Dolor</span></span></li>#}
							</ul>
						</div>
                <hr />
					</section>

    {% endfor %}

<div style='text-align: center;'>
	<style name="page">
	a,
	a{
		color:yellow;
	}
	a:hover{
		color:red;
	}
	</style>
	<table>
	<td><p><-最新</p></td>
	<td>
	{% if rear %}
		<a href="?page={{nex}}"><span><<</span></a>
	{% else %}
		<p><<</p>
	{% endif %}
	</td>

	{# 打印所有页码 #}
	{% for page in page_list %}
		<td>
		{% if page == page_num %}
			<a href="?page={{page}}" style="color:red;">
				<span>
					{{page}}
				</span>
			</a>
		{% else %}
			{% if page == '...' %}
				<a>{{page}}</a>
			{% else %}
				<a href="?page={{page}}">
				<span>
					{{page}}
				</span>
				</a>
			{% endif %}
		{% endif %}
		</td>
	{% endfor %}
	
	<td>
	{% if head %}
		<a href="?page={{pre}}"><span>>></span></a>
	{% else %}
		<p>>></p>
	{% endif %}
    </td>
    <td>最早-></td>
    </table>
</div>


                    <!--<div class="chs">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>-->

				<!-- Two -->
					<section id="two" class="wrapper alt style2">
						<section class="spotlight">
							<div class="image"><img src="https://static2.ichunqiu.com/icq/resources/images/racing/banner.jpg" alt="" /></div><div class="content">
								<h2><a href="https://www.ichunqiu.com/competition" target="_blank">i 春秋 ctf时间表</a> <br /></h2>
								<!--<p>Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.</p>-->
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img src="/static/images/hck.jpg" alt="" /></div><div class="content">
								<h2><a href="http://www.shiyanbar.com/ctf/time" >实验吧CTF TIME</a> <br /></h2>
								<!--<p>Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.</p>-->
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img src="/static/images/ctftime.png" alt="" /></div><div class="content">
								<h2><a href="https://ctftime.org/" target="_blank">CTF TIME</a> <br /></h2>
							</div>
						</section>
					</section>

				<!-- Three -->
					<!--<section id="three" class="wrapper style3 special">-->
						<!--<div class="inner">-->
							<!--<header class="major">-->
								<!--<h2>Accumsan mus tortor nunc aliquet</h2>-->
								<!--<p>Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend<br />-->
								<!--fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.</p>-->
							<!--</header>-->
							<!--<ul class="features">-->
								<!--<li class="icon fa-paper-plane-o">-->
									<!--<h3>Arcu accumsan</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
								<!--<li class="icon fa-laptop">-->
									<!--<h3>Ac Augue Eget</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
								<!--<li class="icon fa-code">-->
									<!--<h3>Mus Scelerisque</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
								<!--<li class="icon fa-headphones">-->
									<!--<h3>Mauris Imperdiet</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
								<!--<li class="icon fa-heart-o">-->
									<!--<h3>Aenean Primis</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
								<!--<li class="icon fa-flag-o">-->
									<!--<h3>Tortor Ut</h3>-->
									<!--<p>Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.</p>-->
								<!--</li>-->
							<!--</ul>-->
						<!--</div>-->
					<!--</section>-->

				<!-- CTA -->
{#					<section id="cta" class="wrapper style4">#}
{#						<div class="inner">#}
{#							<header>#}
{#								<h2>Arcue ut vel commodo</h2>#}
{#								<p>Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla.</p>#}
{#							</header>#}
{#							<ul class="actions vertical">#}
{#								<li><a href="#" class="button fit special">Activate</a></li>#}
{#								<li><a href="#" class="button fit">Learn More</a></li>#}
{#							</ul>#}
{#						</div>#}
{#					</section>#}

				<!-- Footer -->
{% endblock %}